{{- define "common.pvc.tpl" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass | default "microk8s-hostpath" }}"
  {{- end }}
  {{- end }}
  volumeName: {{ include "common.pvName" . }}
{{- end -}}

{{- define "common.pvc" -}}
{{- include "common.util.merge" (append . "common.pvc.tpl") -}}
{{- end -}}